[package]
name = "levels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# audio
cpal = "0.13"


# error handling
color-eyre = "0.5"
eyre = "0.6"
thiserror = "1.0"
